# Generated by Django 4.2.29 on 2026-03-19 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receive',
            fields=[
                ('l_id', models.AutoField(primary_key=True, serialize=False)),
                ('diary_number', models.IntegerField(default=1)),
                ('letter_number', models.CharField(max_length=100)),
                ('letter_date', models.DateField()),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_address', models.TextField(blank=True, null=True)),
                ('sender_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('date_of_receipt', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('current_status', models.CharField(choices=[('NEW', 'NEW'), ('DISPATCHED', 'DISPATCHED'), ('RECEIVED', 'RECEIVED')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('dispatch_id', models.AutoField(primary_key=True, serialize=False)),
                ('receiver_officer_department', models.CharField(max_length=255)),
                ('dispatch_number', models.CharField(max_length=100)),
                ('receiver_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('status', models.CharField(choices=[('NOT_RECEIVED', 'NOT_RECEIVED'), ('RECEIVED', 'RECEIVED')], default='NOT_RECEIVED', max_length=20)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='register.receive')),
            ],
        ),
    ]
