# Generated by Django 4.2.29 on 2026-03-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='signature_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
