# Generated by Django 4.2.29 on 2026-03-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_dispatch_signature_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receive',
            name='date_of_receipt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
