# Generated by Django 4.2.29 on 2026-04-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_receive_date_of_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receive',
            name='letter_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipt_images/'),
        ),
    ]
